[package]
name = "todo_softbuffer"
version.workspace = true
edition.workspace = true

[dependencies]
velona.workspace = true
velona_renderer_vello_cpu.workspace = true
env_logger.workspace = true
log.workspace = true
hotpath = { workspace = true, optional = true }
winit = { workspace = true }
softbuffer = { workspace = true }
vello_cpu = { workspace = true }

[features]
hotpath = ["dep:hotpath", "velona/hotpath", "hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
multithreading = ["vello_cpu/multithreading"]
