[package]
name = "velona_renderer_vello_hybrid"
version.workspace = true
edition.workspace = true

[dependencies]
velona_renderer.workspace = true
imaging = { workspace = true }
wgpu_context.workspace = true
futures-channel.workspace = true
peniko.workspace = true
kurbo.workspace = true
pollster.workspace = true
debug_timer.workspace = true
# hotpath = {workspace = true, optional=true}
vello_hybrid = { workspace = true, features = ["wgpu", "text"] }
vello_common.workspace = true
wgpu.workspace = true
glifo = { workspace = true, features = ["std"] }

[features]
log_frame_times = ["debug_timer/enable"]
# hotpath = ["dep:hotpath"]
