[package]
name = "velona_core"
version.workspace = true
edition.workspace = true

[dependencies]
accesskit_winit.workspace = true
any_spawner.workspace = true
async-task.workspace = true
masonry_imaging.workspace = true
masonry_core.workspace = true
reactive_graph = { workspace = true, features = ["effects", "sandboxed-arenas"] }
masonry_raw_box = { workspace = true }
thiserror.workspace = true
winit.workspace = true
log.workspace = true
# TODO remove this
non-exhaustive.workspace = true
send_wrapper.workspace = true
# TODO remove this in favor of atomics counter
# uuid = { workspace = true, features = ["v4"] }
ui-events-winit.workspace = true
# parking_lot = "0.12"
copypasta.workspace = true
futures-channel.workspace = true
hotpath = { version = "0.16", optional = true }
# TODO add anyrender for rendering simplicity
imaging.workspace = true
velona_renderer.workspace = true
flume.workspace = true

[dev-dependencies]
masonry = { workspace = true }

[features]
# default = ["testing"]
hotpath = ["dep:hotpath"]
# testing = []
