[package]
name = "custom_title_bar"
version.workspace = true
edition.workspace = true

[dependencies]
velona = { workspace = true, default-features = true }
velona_renderer_vello_hybrid.workspace = true
env_logger.workspace = true
log.workspace = true
hotpath = { workspace = true, optional = true }
async-io = { workspace = true }
futures-util = { workspace = true }
clonelicious = "10"
tracing = { workspace = true }
masonry_raw_box = { workspace = true }
masonry_widget_wrappers = { workspace = true }

[features]
hotpath = ["dep:hotpath", "velona/hotpath", "hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
