[package]
name = "todo_vello_hybrid"
version.workspace = true
edition.workspace = true

[dependencies]
velona.workspace = true
velona_renderer_vello_hybrid.workspace = true
env_logger.workspace = true
log.workspace = true
hotpath = { workspace = true, optional = true }

[features]
hotpath = ["dep:hotpath", "velona/hotpath", "hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
