[package]
name = "velona_router"
version.workspace = true
edition.workspace = true

[dependencies]
velona_core = { workspace = true }
masonry_raw_box = { workspace = true }
# reactive_stores = { workspace = true }
derive_more = { workspace = true, features = ["debug"] }
tree_arena = { workspace = true, default-features = true }
thiserror = { workspace = true }
url = { workspace = true }
