[package]
name = "velona"
version.workspace = true
edition.workspace = true

[dependencies]
masonry.workspace = true
thiserror.workspace = true
log.workspace = true
hotpath = { workspace = true, optional = true }
# TODO add anyrender for rendering simplicity
resvg.workspace = true
velona_core = { workspace = true }
velona_core_child = { workspace = true, features = ["masonry_widget_impls"] }

[features]
hotpath = ["dep:hotpath", "velona_core/hotpath"]
hotpath-run = ["hotpath", "hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[dev-dependencies]
env_logger.workspace = true
image = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time"] }
anyhow.workspace = true
velona_renderer_vello.workspace = true
derive_more = { workspace = true, features = ["display", "from_str"] }
enum_all_variants = { workspace = true }
