[package]
name = "velona"
version.workspace = true
edition.workspace = true

[dependencies]
masonry.workspace = true
thiserror.workspace = true
log.workspace = true
hotpath = { workspace = true, optional = true }
# TODO add anyrender for rendering simplicity
resvg.workspace = true
velona_core = { workspace = true }
velona_core_child = { workspace = true, features = ["masonry_widget_impls"] }
velona_scoped_styling = { workspace = true }

[features]
hotpath = ["dep:hotpath", "velona_core/hotpath"]
subsecond = ["velona_core/subsecond"]
